# -*- coding: utf-8 -*-
{
    'name': 'Bista Document Management System',
    'desc': 'Bista Document Management System',
    'author': 'Krish Manek',
    'depends': ['base','sale','product'],
    'sequence': 1,
    'application': 'true',
    'version': '1.0',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/mail_template.xml',
        'data/system_param.xml',
        'views/documents_custom_view.xml',
        'views/doc_tag_master_view.xml',
        'views/res_partner_view.xml',
        'views/product_product_view.xml',
        'wizard/add_doc_wizard.xml',
        'views/sale_order_view.xml',
        'views/stock_picking.xml',
        'views/documents_order_line_view.xml',
        'views/student_activity_view.xml',
        'report/stock_report_deliveryslip.xml',
        'report/sale_report_view.xml',
        'report/sale_report_view_inh.xml',  
    ],
}